# Use Node base image
FROM node:18

# Set working directory inside container
WORKDIR /app

# Copy all files into container
COPY . .

# Install dependencies
RUN npm install -g yarn
RUN yarn install --ignore-engines

# Expose the port
EXPOSE 80

# Start Outline server
CMD ["yarn", "start"]
